# Generated by Django 4.2.16 on 2026-06-26 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('type_concession', models.CharField(choices=[('TEMPORAIRE', 'Temporaire (5 ans)'), ('RENOUVELABLE', 'Renouvelable (15 ans)'), ('PERPETUELLE', 'Perpétuelle')], max_length=20)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('RESILIEE', 'Résiliée'), ('EN_RENOUVELLEMENT', 'En cours de renouvellement')], default='ACTIVE', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date_alerte', models.DateField(blank=True, null=True)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documents_legaux', models.FileField(blank=True, upload_to='concessions/docs/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concessions_creees', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='concession', to='reservations.reservation')),
                ('titulaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concession',
                'db_table': 'concessions',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='DemandeExhumation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('SOUMISE', 'Soumise'), ('EN_INSTRUCTION', 'En instruction'), ('AUTORISEE', 'Autorisée'), ('REFUSEE', 'Refusée'), ('EXECUTEE', 'Exécutée')], default='SOUMISE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_execution_prevue', models.DateField(blank=True, null=True)),
                ('date_execution_reelle', models.DateField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True)),
                ('autorisation_pdf', models.FileField(blank=True, upload_to='exhumations/autorisations/')),
                ('pv_pdf', models.FileField(blank=True, upload_to='exhumations/pv/')),
                ('autorise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_autorisees', to=settings.AUTH_USER_MODEL)),
                ('concession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhumations', to='concessions.concession')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhumations_demandees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Demande d'exhumation",
                'db_table': 'exhumations',
                'ordering': ['-date_demande'],
            },
        ),
    ]
