# Generated by Django 4.2.16 on 2026-06-26 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_notif', models.CharField(choices=[('MFA', 'Code MFA'), ('CONFIRMATION_RESERVATION', 'Confirmation réservation'), ('FACTURE', 'Facture'), ('ALERTE_EXPIRATION', 'Alerte expiration concession'), ('ALERTE_PLACES', 'Alerte places critiques'), ('RETARD_PAIEMENT', 'Retard de paiement'), ('VALIDATION_RESERVATION', 'Validation réservation'), ('ANNULATION_RESERVATION', 'Annulation réservation')], max_length=30)),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('contenu_html', models.TextField(blank=True)),
                ('envoyee', models.BooleanField(default=False)),
                ('lue', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('erreur', models.TextField(blank=True)),
                ('tentatives', models.IntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'db_table': 'notifications',
                'ordering': ['-cree_le'],
            },
        ),
    ]
