# Generated by Django 4.2.16 on 2026-06-26 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('type_zone', models.CharField(choices=[('SECTION', 'Section'), ('BLOC', 'Bloc'), ('ALLEE', 'Allée principale'), ('NON_EXPLOITABLE', 'Zone non exploitable')], default='SECTION', max_length=20)),
                ('superficie_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('couleur_carte', models.CharField(default='#3b82f6', max_length=7)),
                ('latitude_centre', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude_centre', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('active', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zone',
                'db_table': 'zones',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cimetiere', models.CharField(default='Cimetière GI2', max_length=200)),
                ('adresse', models.TextField(default='')),
                ('telephone_contact', models.CharField(default='', max_length=20)),
                ('email_contact', models.EmailField(default='', max_length=254)),
                ('superficie_totale_m2', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('taille_caveau_longueur', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('taille_caveau_largeur', models.DecimalField(decimal_places=2, default=1.2, max_digits=5)),
                ('largeur_allee_m', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('tarif_concession_temporaire', models.DecimalField(decimal_places=2, default=150000, max_digits=10)),
                ('tarif_concession_perpetuelle', models.DecimalField(decimal_places=2, default=500000, max_digits=10)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration',
                'db_table': 'configurations',
            },
        ),
        migrations.CreateModel(
            name='Caveau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20)),
                ('rangee', models.IntegerField(default=1)),
                ('colonne', models.IntegerField(default=1)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé / En attente'), ('OCCUPE', 'Occupé / Validé'), ('NON_EXPLOITABLE', 'Non exploitable'), ('ENTRETIEN', 'En entretien')], default='DISPONIBLE', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, default=0, max_digits=11)),
                ('superficie_m2', models.DecimalField(decimal_places=2, default=3.0, max_digits=6)),
                ('profondeur_m', models.DecimalField(decimal_places=2, default=1.8, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caveaux_modifies', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caveaux', to='terrain.zone')),
            ],
            options={
                'verbose_name': 'Caveau',
                'db_table': 'caveaux',
                'ordering': ['zone', 'rangee', 'colonne'],
                'unique_together': {('zone', 'numero')},
            },
        ),
    ]
