# Generated by Django 4.2.16 on 2026-07-13 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CHANGEMENT_STATUT_CAVEAU', 'Changement statut caveau'), ('VALIDATION_RESERVATION', 'Validation réservation'), ('ANNULATION_RESERVATION', 'Annulation réservation'), ('PAIEMENT_CONFIRME', 'Paiement confirmé'), ('CONNEXION', 'Connexion utilisateur'), ('CREATION_CONCESSION', 'Création concession'), ('AUTORISATION_EXHUMATION', 'Autorisation exhumation'), ('MODIFICATION_CONFIG', 'Modification configuration')], max_length=50)),
                ('objet_type', models.CharField(max_length=50)),
                ('objet_id', models.CharField(max_length=100)),
                ('ancienne_valeur', models.JSONField(blank=True, default=dict)),
                ('nouvelle_valeur', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-horodatage'],
            },
        ),
    ]
