# Generated by Django 4.2.16 on 2026-06-26 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('canal', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money (MTN)'), ('AIRTEL_MONEY', 'Airtel Money'), ('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('INITIE', 'Initié'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='XAF', max_length=3)),
                ('numero_telephone', models.CharField(blank=True, max_length=20)),
                ('reference_operateur', models.CharField(blank=True, max_length=100)),
                ('transaction_id_externe', models.CharField(blank=True, max_length=200)),
                ('date_initiation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('reponse_api', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'db_table': 'paiements',
                'ordering': ['-date_initiation'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMobileMoney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_operation', models.CharField(choices=[('DEBIT', 'Débit client'), ('WEBHOOK', 'Webhook reçu'), ('STATUT', 'Vérification statut')], max_length=20)),
                ('url_appelee', models.CharField(max_length=500)),
                ('payload_envoi', models.JSONField(default=dict)),
                ('reponse', models.JSONField(default=dict)),
                ('code_http', models.IntegerField()),
                ('duree_ms', models.IntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='paiements.paiement')),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money',
                'db_table': 'transactions_mm',
                'ordering': ['-cree_le'],
            },
        ),
    ]
